// FIELDMEMORY seed data — realistic industrial maintenance history.
// Relationships matter: C-17 has a recurring E204 fault where a bearing
// replacement FAILED and an alignment correction RESOLVED the same code.
// Every memory mirrors a closed incident; outcomes repeat across machines.

export type SeedMachine = {
  code: string;
  name: string;
  type: string;
  location: string;
  status: "online" | "degraded" | "offline" | "maintenance";
  operatingHours: number;
  lastService: string;
  critical: boolean;
  telemetry: { temperature: number; vibration: number; pressure: number };
  telemetryHistory: {
    temperature: number[];
    vibration: number[];
    pressure: number[];
  };
  assetNumber: string;
  manufacturer: string;
  installedYear: number;
};

export type SeedIncident = {
  code: string;
  machineCode: string;
  date: string;
  fault: string;
  errorCode: string;
  severity: "critical" | "high" | "medium" | "low";
  status: "open" | "resolved" | "failed" | "partial";
  action?: string;
  outcome?: "resolved" | "failed" | "partial";
  technician?: string;
  technicianNotes?: string;
  telemetry: { temperature: number; vibration: number; pressure: number };
};

// ---- Machines ----------------------------------------------------------

export const seedMachines: SeedMachine[] = [
  {
    code: "C-17",
    name: "Compressor C-17",
    type: "Centrifugal Compressor",
    location: "Plant A - Unit 3",
    status: "degraded",
    operatingHours: 12480,
    lastService: "2026-08-03",
    critical: true,
    telemetry: { temperature: 94, vibration: 8.4, pressure: 6.1 },
    telemetryHistory: {
      temperature: [71, 73, 72, 75, 74, 78, 77, 81, 83, 86, 88, 90, 92, 94],
      vibration: [3.1, 3.3, 3.2, 3.8, 4.1, 4.6, 5.2, 5.8, 6.4, 7.0, 7.6, 8.0, 8.2, 8.4],
      pressure: [7.2, 7.1, 7.3, 7.0, 6.9, 6.8, 6.7, 6.6, 6.5, 6.4, 6.3, 6.2, 6.15, 6.1],
    },
    assetNumber: "CMP-2201-A3",
    manufacturer: "Atlas-Copco",
    installedYear: 2019,
  },
  {
    code: "P-04",
    name: "Hydraulic Pump P-04",
    type: "Hydraulic Pump",
    location: "Plant A - Unit 1",
    status: "online",
    operatingHours: 9310,
    lastService: "2026-09-02",
    critical: false,
    telemetry: { temperature: 62, vibration: 3.2, pressure: 12.4 },
    telemetryHistory: {
      temperature: [58, 59, 61, 60, 62, 61, 63, 62],
      vibration: [3.0, 3.1, 3.2, 3.1, 3.3, 3.2, 3.2, 3.2],
      pressure: [12.1, 12.2, 12.4, 12.3, 12.4, 12.5, 12.4, 12.4],
    },
    assetNumber: "HYD-1180-A1",
    manufacturer: "Bosch Rexroth",
    installedYear: 2021,
  },
  {
    code: "G-02",
    name: "Generator G-02",
    type: "Diesel Generator",
    location: "Plant B - Power House",
    status: "degraded",
    operatingHours: 21240,
    lastService: "2026-06-18",
    critical: true,
    telemetry: { temperature: 88, vibration: 6.8, pressure: 4.9 },
    telemetryHistory: {
      temperature: [80, 82, 81, 84, 85, 87, 88, 88],
      vibration: [5.5, 5.7, 6.0, 6.2, 6.4, 6.6, 6.7, 6.8],
      pressure: [5.2, 5.1, 5.1, 5.0, 5.0, 4.95, 4.9, 4.9],
    },
    assetNumber: "GEN-0902-B1",
    manufacturer: "Caterpillar",
    installedYear: 2017,
  },
  {
    code: "M-12",
    name: "Cooling Motor M-12",
    type: "Induction Motor",
    location: "Plant A - Unit 2",
    status: "online",
    operatingHours: 6420,
    lastService: "2026-08-28",
    critical: false,
    telemetry: { temperature: 55, vibration: 2.1, pressure: 3.4 },
    telemetryHistory: {
      temperature: [52, 53, 54, 53, 55, 54, 55, 55],
      vibration: [1.9, 2.0, 2.1, 2.0, 2.2, 2.1, 2.1, 2.1],
      pressure: [3.3, 3.4, 3.4, 3.5, 3.4, 3.4, 3.4, 3.4],
    },
    assetNumber: "MTR-0733-A2",
    manufacturer: "ABB",
    installedYear: 2022,
  },
  {
    code: "D-08",
    name: "Conveyor Drive D-08",
    type: "Conveyor Drive",
    location: "Plant B - Line 4",
    status: "maintenance",
    operatingHours: 15870,
    lastService: "2026-09-12",
    critical: false,
    telemetry: { temperature: 48, vibration: 2.8, pressure: 2.2 },
    telemetryHistory: {
      temperature: [46, 47, 48, 47, 48, 49, 48, 48],
      vibration: [2.6, 2.7, 2.8, 2.8, 2.9, 2.8, 2.8, 2.8],
      pressure: [2.1, 2.2, 2.2, 2.3, 2.2, 2.2, 2.2, 2.2],
    },
    assetNumber: "CNV-0440-B4",
    manufacturer: "SEW-Eurodrive",
    installedYear: 2020,
  },
  {
    code: "A-06",
    name: "Air Compressor A-06",
    type: "Rotary Screw Compressor",
    location: "Plant A - Utilities",
    status: "online",
    operatingHours: 11230,
    lastService: "2026-07-21",
    critical: false,
    telemetry: { temperature: 70, vibration: 4.4, pressure: 8.2 },
    telemetryHistory: {
      temperature: [66, 67, 68, 69, 70, 69, 70, 70],
      vibration: [4.0, 4.1, 4.2, 4.3, 4.4, 4.4, 4.4, 4.4],
      pressure: [8.0, 8.1, 8.2, 8.1, 8.2, 8.2, 8.2, 8.2],
    },
    assetNumber: "ACM-1620-A0",
    manufacturer: "Kaeser",
    installedYear: 2020,
  },
  {
    code: "P-09",
    name: "Cooling Pump P-09",
    type: "Centrifugal Pump",
    location: "Plant B - Chiller Bay",
    status: "online",
    operatingHours: 8850,
    lastService: "2026-08-15",
    critical: false,
    telemetry: { temperature: 58, vibration: 2.6, pressure: 5.6 },
    telemetryHistory: {
      temperature: [55, 56, 57, 56, 58, 57, 58, 58],
      vibration: [2.4, 2.5, 2.6, 2.5, 2.7, 2.6, 2.6, 2.6],
      pressure: [5.4, 5.5, 5.6, 5.5, 5.6, 5.6, 5.6, 5.6],
    },
    assetNumber: "PMP-2090-B5",
    manufacturer: "Grundfos",
    installedYear: 2021,
  },
  {
    code: "T-03",
    name: "Turbine T-03",
    type: "Steam Turbine",
    location: "Plant B - Power House",
    status: "degraded",
    operatingHours: 32410,
    lastService: "2026-05-30",
    critical: true,
    telemetry: { temperature: 82, vibration: 7.2, pressure: 16.8 },
    telemetryHistory: {
      temperature: [76, 77, 78, 79, 80, 81, 82, 82],
      vibration: [6.2, 6.4, 6.6, 6.8, 7.0, 7.1, 7.2, 7.2],
      pressure: [17.2, 17.1, 17.0, 17.0, 16.9, 16.9, 16.8, 16.8],
    },
    assetNumber: "TRB-3301-B2",
    manufacturer: "Siemens Energy",
    installedYear: 2015,
  },
];

// ---- Incidents (28 closed + 1 open) -------------------------------------

export const seedIncidents: SeedIncident[] = [
  // ===== Compressor C-17 — the recurring E204 storyline =====
  {
    code: "INC-C17-1125",
    machineCode: "C-17",
    date: "2025-11-25T08:40:00Z",
    fault: "High vibration",
    errorCode: "E204",
    severity: "high",
    status: "resolved",
    action: "Lubrication service",
    outcome: "resolved",
    technician: "Arjun K.",
    technicianNotes:
      "Lube oil level had dropped below sight-glass minimum. Topped up and replaced oil. Vibration settled to 3.4 mm/s within an hour.",
    telemetry: { temperature: 76, vibration: 6.2, pressure: 6.9 },
  },
  {
    code: "INC-C17-0326",
    machineCode: "C-17",
    date: "2026-03-26T14:05:00Z",
    fault: "High temperature",
    errorCode: "E112",
    severity: "medium",
    status: "partial",
    action: "Oil cooler descale",
    outcome: "partial",
    technician: "Meera S.",
    technicianNotes:
      "Descaled oil cooler; discharge temp fell from 83°C to 74°C but crept back over a week. Suspect internal fouling — schedule cooler inspection.",
    telemetry: { temperature: 83, vibration: 4.8, pressure: 6.7 },
  },
  {
    code: "INC-C17-0626",
    machineCode: "C-17",
    date: "2026-06-14T09:15:00Z",
    fault: "High temperature",
    errorCode: "E112",
    severity: "medium",
    status: "resolved",
    action: "Lubrication filter replacement",
    outcome: "resolved",
    technician: "Karthik R.",
    technicianNotes:
      "Low lubrication pressure found. Filter differential 1.4 bar over limit. Replaced filter and checked oil flow to both bearing housings. Temperature normal after 2 hours.",
    telemetry: { temperature: 81, vibration: 4.2, pressure: 6.6 },
  },
  {
    code: "INC-C17-0826",
    machineCode: "C-17",
    date: "2026-08-03T11:30:00Z",
    fault: "High vibration",
    errorCode: "E204",
    severity: "high",
    status: "resolved",
    action: "Alignment correction",
    outcome: "resolved",
    technician: "Meera S.",
    technicianNotes:
      "Shaft alignment corrected. Machine returned to normal. Laser alignment found 0.31 mm offset at coupling; corrected to within 0.03 mm.",
    telemetry: { temperature: 78, vibration: 7.9, pressure: 6.8 },
  },
  {
    code: "INC-C17-0926",
    machineCode: "C-17",
    date: "2026-09-19T16:45:00Z",
    fault: "High vibration",
    errorCode: "E204",
    severity: "critical",
    status: "failed",
    action: "Bearing replacement",
    outcome: "failed",
    technician: "Arjun K.",
    technicianNotes:
      "Bearing replaced but vibration remained high.DE housing had spalling; fitted new 6316-C3. Vibration still 8.1 mm/s after restart. Suspect root cause upstream of bearing.",
    telemetry: { temperature: 91, vibration: 8.1, pressure: 6.2 },
  },
  {
    code: "INC-C17-0926b",
    machineCode: "C-17",
    date: "2026-09-26T10:24:00Z",
    fault: "High vibration / High temperature",
    errorCode: "E204",
    severity: "critical",
    status: "open",
    telemetry: { temperature: 94, vibration: 8.4, pressure: 6.1 },
  },

  // ===== Hydraulic Pump P-04 =====
  {
    code: "INC-P04-0126",
    machineCode: "P-04",
    date: "2026-01-12T07:50:00Z",
    fault: "Low system pressure",
    errorCode: "E301",
    severity: "medium",
    status: "resolved",
    action: "Relief valve recalibration",
    outcome: "resolved",
    technician: "Sana P.",
    technicianNotes:
      "Relief valve creeping open at 11.8 bar. Recalibrated set point to 12.6 bar and verified with dead-weight tester.",
    telemetry: { temperature: 60, vibration: 3.0, pressure: 10.9 },
  },
  {
    code: "INC-P04-0526",
    machineCode: "P-04",
    date: "2026-05-08T13:20:00Z",
    fault: "Hydraulic fluid overheating",
    errorCode: "E118",
    severity: "medium",
    status: "resolved",
    action: "Heat exchanger cleaning",
    outcome: "resolved",
    technician: "Vikram D.",
    technicianNotes:
      "Heat exchanger fins clogged with dust. Compressed-air cleaning restored ΔT; fluid temp back under 60°C.",
    telemetry: { temperature: 74, vibration: 3.4, pressure: 12.2 },
  },
  {
    code: "INC-P04-0826",
    machineCode: "P-04",
    date: "2026-08-19T10:10:00Z",
    fault: "Intermittent pressure drop",
    errorCode: "E301",
    severity: "low",
    status: "resolved",
    action: "Suction strainer replacement",
    outcome: "resolved",
    technician: "Sana P.",
    technicianNotes:
      "Cavitation noise audible on start-up. Suction strainer 70% blocked; replaced and de-aerated circuit.",
    telemetry: { temperature: 63, vibration: 3.6, pressure: 11.6 },
  },

  // ===== Generator G-02 =====
  {
    code: "INC-G02-0226",
    machineCode: "G-02",
    date: "2026-02-14T06:30:00Z",
    fault: "Coolant temperature high",
    errorCode: "E210",
    severity: "high",
    status: "resolved",
    action: "Radiator core replacement",
    outcome: "resolved",
    technician: "Vikram D.",
    technicianNotes:
      "Radiator core internally corroded. Replaced core, flushed jacket, refilled with 50/50 coolant. Load test at 80% for 2h stable.",
    telemetry: { temperature: 96, vibration: 5.8, pressure: 5.1 },
  },
  {
    code: "INC-G02-0526",
    machineCode: "G-02",
    date: "2026-05-22T15:45:00Z",
    fault: "Governor hunting",
    errorCode: "E405",
    severity: "medium",
    status: "resolved",
    action: "Governor linkage service",
    outcome: "resolved",
    technician: "Arjun K.",
    technicianNotes:
      "Governor linkage sticking due to gummed oil. Cleaned, re-greased, droop reset. Frequency stable at 50.0 Hz.",
    telemetry: { temperature: 85, vibration: 6.0, pressure: 5.2 },
  },
  {
    code: "INC-G02-0726",
    machineCode: "G-02",
    date: "2026-07-11T09:00:00Z",
    fault: "High vibration",
    errorCode: "E204",
    severity: "high",
    status: "failed",
    action: "Bearing replacement",
    outcome: "failed",
    technician: "Karthik R.",
    technicianNotes:
      "Replaced DE bearing on alternator. Vibration improved marginally (7.1 to 6.6 mm/s) but returned within 48h. Rotor balancing suspected.",
    telemetry: { temperature: 87, vibration: 7.1, pressure: 5.0 },
  },
  {
    code: "INC-G02-0926",
    machineCode: "G-02",
    date: "2026-09-08T12:40:00Z",
    fault: "Exhaust smoke at load",
    errorCode: "E330",
    severity: "medium",
    status: "partial",
    action: "Injector servicing",
    outcome: "partial",
    technician: "Vikram D.",
    technicianNotes:
      "Two injectors re-calibrated, smoke reduced but still visible above 75% load. Fuel analysis pending — possible cetane issue.",
    telemetry: { temperature: 88, vibration: 6.8, pressure: 4.9 },
  },

  // ===== Cooling Motor M-12 =====
  {
    code: "INC-M12-0426",
    machineCode: "M-12",
    date: "2026-04-03T08:15:00Z",
    fault: "Winding temperature alarm",
    errorCode: "E501",
    severity: "medium",
    status: "resolved",
    action: "Cooling fan cleaning",
    outcome: "resolved",
    technician: "Sana P.",
    technicianNotes:
      "Cowl screen blocked with fibre dust. Cleaned fan cowl and frame air paths; winding temp back to 68°C from 91°C.",
    telemetry: { temperature: 91, vibration: 2.3, pressure: 3.5 },
  },
  {
    code: "INC-M12-0826b",
    machineCode: "M-12",
    date: "2026-08-14T11:05:00Z",
    fault: "Bearing noise",
    errorCode: "E204",
    severity: "low",
    status: "resolved",
    action: "Bearing lubrication",
    outcome: "resolved",
    technician: "Karthik R.",
    technicianNotes:
      "NDE bearing dry. Greased with correct quantity (12 g, 6312-2Z). Noise gone; vibration down to 2.0 mm/s.",
    telemetry: { temperature: 57, vibration: 3.8, pressure: 3.4 },
  },

  // ===== Conveyor Drive D-08 =====
  {
    code: "INC-D08-0326",
    machineCode: "D-08",
    date: "2026-03-09T10:55:00Z",
    fault: "Belt tracking drift",
    errorCode: "E420",
    severity: "low",
    status: "resolved",
    action: "Pulley alignment",
    outcome: "resolved",
    technician: "Meera S.",
    technicianNotes:
      "Head pulley out of square by 2 mm. Re-squared and re-tensioned belt to 4.5% elongation spec.",
    telemetry: { temperature: 51, vibration: 3.2, pressure: 2.2 },
  },
  {
    code: "INC-D08-0626",
    machineCode: "D-08",
    date: "2026-06-27T14:30:00Z",
    fault: "Gearbox oil leak",
    errorCode: "E115",
    severity: "medium",
    status: "resolved",
    action: "Shaft seal replacement",
    outcome: "resolved",
    technician: "Vikram D.",
    technicianNotes:
      "Input shaft seal hardened and cracked. Replaced seal, checked breather (was plugged), cleaned breather and refilled to sight glass.",
    telemetry: { temperature: 63, vibration: 3.4, pressure: 2.3 },
  },
  {
    code: "INC-D08-0926",
    machineCode: "D-08",
    date: "2026-09-12T09:20:00Z",
    fault: "Vibration spike at speed",
    errorCode: "E204",
    severity: "high",
    status: "partial",
    action: "Pulley lagging repair",
    outcome: "partial",
    technician: "Arjun K.",
    technicianNotes:
      "Re-lagged head pulley. Vibration reduced 5.1 to 3.4 mm/s but slight roughness remains at 42 Hz. Monitor trend.",
    telemetry: { temperature: 55, vibration: 5.1, pressure: 2.2 },
  },

  // ===== Air Compressor A-06 =====
  {
    code: "INC-A06-0126",
    machineCode: "A-06",
    date: "2026-01-28T08:00:00Z",
    fault: "Low discharge pressure",
    errorCode: "E301",
    severity: "medium",
    status: "resolved",
    action: "Air/oil separator replacement",
    outcome: "resolved",
    technician: "Sana P.",
    technicianNotes:
      "Separator element ΔP 0.9 bar. Replaced element, pressure recovered to 8.2 bar. Logged element in spares tracking.",
    telemetry: { temperature: 75, vibration: 4.2, pressure: 7.1 },
  },
  {
    code: "INC-A06-0626",
    machineCode: "A-06",
    date: "2026-06-05T13:40:00Z",
    fault: "Unloader fault",
    errorCode: "E502",
    severity: "low",
    status: "resolved",
    action: "Solenoid valve replacement",
    outcome: "resolved",
    technician: "Karthik R.",
    technicianNotes:
      "Unloader solenoid coil open-circuit. Replaced valve; unload cycle verified at 8.6 bar.",
    telemetry: { temperature: 72, vibration: 4.6, pressure: 8.0 },
  },

  // ===== Cooling Pump P-09 =====
  {
    code: "INC-P09-0226",
    machineCode: "P-09",
    date: "2026-02-20T07:25:00Z",
    fault: "Cavitation noise",
    errorCode: "E310",
    severity: "medium",
    status: "resolved",
    action: "Suction strainer cleaning",
    outcome: "resolved",
    technician: "Meera S.",
    technicianNotes:
      "Strainer basket 60% blocked with scale. Cleaned; NPSH margin restored, noise gone.",
    telemetry: { temperature: 61, vibration: 3.9, pressure: 5.0 },
  },
  {
    code: "INC-P09-0726",
    machineCode: "P-09",
    date: "2026-07-19T15:10:00Z",
    fault: "Seal weeping",
    errorCode: "E118",
    severity: "low",
    status: "resolved",
    action: "Mechanical seal replacement",
    outcome: "resolved",
    technician: "Sana P.",
    technicianNotes:
      "Seal faces scored. Replaced mechanical seal and throat bushing; leak rate now zero.",
    telemetry: { temperature: 59, vibration: 2.8, pressure: 5.4 },
  },

  // ===== Turbine T-03 =====
  {
    code: "INC-T03-0126",
    machineCode: "T-03",
    date: "2026-01-15T11:50:00Z",
    fault: "Governing valve sticking",
    errorCode: "E405",
    severity: "high",
    status: "resolved",
    action: "Governing valve overhaul",
    outcome: "resolved",
    technician: "Arjun K.",
    technicianNotes:
      "Valve stem deposits causing stick-slip. Overhauled valve, cleaned stem, renewed packing. Response linear across 20-100%.",
    telemetry: { temperature: 79, vibration: 6.9, pressure: 17.4 },
  },
  {
    code: "INC-T03-0426",
    machineCode: "T-03",
    date: "2026-04-18T10:05:00Z",
    fault: "High vibration",
    errorCode: "E204",
    severity: "high",
    status: "failed",
    action: "Bearing replacement",
    outcome: "failed",
    technician: "Karthik R.",
    technicianNotes:
      "Replaced #2 journal bearing. Vibration unchanged (7.0 mm/s). Balancing plant visit needed; scheduled for next shutdown window.",
    telemetry: { temperature: 80, vibration: 7.0, pressure: 17.1 },
  },
  {
    code: "INC-T03-0626",
    machineCode: "T-03",
    date: "2026-06-02T16:20:00Z",
    fault: "High vibration",
    errorCode: "E204",
    severity: "high",
    status: "partial",
    action: "Rotor field balancing",
    outcome: "partial",
    technician: "Vikram D.",
    technicianNotes:
      "Added 34 g correction mass at plane 2. Vibration 7.0 to 5.9 mm/s at rated speed. Third harmonic still elevated; further trim planned.",
    telemetry: { temperature: 81, vibration: 7.0, pressure: 16.9 },
  },
  {
    code: "INC-T03-0826",
    machineCode: "T-03",
    date: "2026-08-09T09:35:00Z",
    fault: "Steam gland leak",
    errorCode: "E210",
    severity: "medium",
    status: "resolved",
    action: "Gland seal renewal",
    outcome: "resolved",
    technician: "Meera S.",
    technicianNotes:
      "Gland packing extruded on HP side. Renewed packing rings, verified vacuum held at -92 kPa.",
    telemetry: { temperature: 83, vibration: 6.8, pressure: 16.7 },
  },

  // ===== Cross-machine: vibration stories that reinforce the pattern =====
  {
    code: "INC-A06-0826",
    machineCode: "A-06",
    date: "2026-08-25T14:15:00Z",
    fault: "High vibration",
    errorCode: "E204",
    severity: "medium",
    status: "resolved",
    action: "Motor alignment correction",
    outcome: "resolved",
    technician: "Meera S.",
    technicianNotes:
      "Compressor-motor coupling misaligned 0.22 mm after foundation work. Laser-aligned; vibration 4.9 to 3.8 mm/s.",
    telemetry: { temperature: 71, vibration: 4.9, pressure: 8.1 },
  },
  {
    code: "INC-P09-0926",
    machineCode: "P-09",
    date: "2026-09-05T08:45:00Z",
    fault: "High vibration",
    errorCode: "E204",
    severity: "medium",
    status: "resolved",
    action: "Bearing replacement",
    outcome: "resolved",
    technician: "Karthik R.",
    technicianNotes:
      "Motor DE bearing fluting from shaft currents confirmed. Replaced bearing and fitted insulated sleeve. Vibration 5.6 to 2.6 mm/s.",
    telemetry: { temperature: 60, vibration: 5.6, pressure: 5.5 },
  },
];

// ---- Memories: one per closed incident, with "what was learned" -----------

export type SeedMemory = {
  code: string;
  incidentCode: string;
  machineCode: string;
  fault: string;
  errorCode: string;
  symptoms: string[];
  diagnosis: string;
  action: string;
  outcome: "resolved" | "failed" | "partial";
  technician: string;
  technicianNotes: string;
  learning: string;
  severity: "critical" | "high" | "medium" | "low";
  timestamp: string;
};

export const seedMemories: SeedMemory[] = [
  {
    code: "MEM-C17-E204-1125",
    incidentCode: "INC-C17-1125",
    machineCode: "C-17",
    fault: "High vibration",
    errorCode: "E204",
    symptoms: ["Vibration 6.2 mm/s", "Lube oil level low"],
    diagnosis: "Lubrication starvation raising bearing friction.",
    action: "Lubrication service",
    outcome: "resolved",
    technician: "Arjun K.",
    technicianNotes:
      "Lube oil level had dropped below sight-glass minimum. Topped up and replaced oil. Vibration settled to 3.4 mm/s within an hour.",
    learning:
      "C-17 vibration events can start as simple lubrication starvation — check oil level and condition before dismantling.",
    severity: "high",
    timestamp: "2025-11-25T08:40:00Z",
  },
  {
    code: "MEM-C17-E112-0326",
    incidentCode: "INC-C17-0326",
    machineCode: "C-17",
    fault: "High temperature",
    errorCode: "E112",
    symptoms: ["Discharge temperature 83°C", "Rising trend"],
    diagnosis: "Fouled oil cooler reducing heat rejection.",
    action: "Oil cooler descale",
    outcome: "partial",
    technician: "Meera S.",
    technicianNotes:
      "Descaled oil cooler; discharge temp fell from 83°C to 74°C but crept back over a week. Suspect internal fouling — schedule cooler inspection.",
    learning:
      "External descale only partially restores C-17 oil-cooler duty; recurring E112 points to internal cooler fouling.",
    severity: "medium",
    timestamp: "2026-03-26T14:05:00Z",
  },
  {
    code: "MEM-C17-E112-0626",
    incidentCode: "INC-C17-0626",
    machineCode: "C-17",
    fault: "High temperature",
    errorCode: "E112",
    symptoms: ["Temperature 81°C", "Low lubrication pressure"],
    diagnosis: "Clogged lube filter starving bearing oil flow.",
    action: "Lubrication filter replacement",
    outcome: "resolved",
    technician: "Karthik R.",
    technicianNotes:
      "Low lubrication pressure found. Filter differential 1.4 bar over limit. Replaced filter and checked oil flow to both bearing housings. Temperature normal after 2 hours.",
    learning:
      "Check lube filter ΔP early on C-17 temperature events — a 1.4 bar differential was the whole fault.",
    severity: "medium",
    timestamp: "2026-06-14T09:15:00Z",
  },
  {
    code: "MEM-C17-E204-0826",
    incidentCode: "INC-C17-0826",
    machineCode: "C-17",
    fault: "High vibration",
    errorCode: "E204",
    symptoms: ["Vibration 7.9 mm/s", "Normal oil pressure"],
    diagnosis: "Coupling misalignment exciting 1× running-speed vibration.",
    action: "Alignment correction",
    outcome: "resolved",
    technician: "Meera S.",
    technicianNotes:
      "Shaft alignment corrected. Machine returned to normal. Laser alignment found 0.31 mm offset at coupling; corrected to within 0.03 mm.",
    learning:
      "C-17 E204 was fully resolved by alignment correction (0.31 mm offset) with no parts replaced.",
    severity: "high",
    timestamp: "2026-08-03T11:30:00Z",
  },
  {
    code: "MEM-C17-E204-0926",
    incidentCode: "INC-C17-0926",
    machineCode: "C-17",
    fault: "High vibration",
    errorCode: "E204",
    symptoms: ["Vibration 8.1 mm/s", "Temperature 91°C"],
    diagnosis: "Bearing wear assumed; replaced DE bearing.",
    action: "Bearing replacement",
    outcome: "failed",
    technician: "Arjun K.",
    technicianNotes:
      "Bearing replaced but vibration remained high. DE housing had spalling; fitted new 6316-C3. Vibration still 8.1 mm/s after restart. Suspect root cause upstream of bearing.",
    learning:
      "Do not repeat bearing replacement without checking alignment and lubrication — it failed to clear E204 on 19 Sep 2026.",
    severity: "critical",
    timestamp: "2026-09-19T16:45:00Z",
  },
  {
    code: "MEM-P04-E301-0126",
    incidentCode: "INC-P04-0126",
    machineCode: "P-04",
    fault: "Low system pressure",
    errorCode: "E301",
    symptoms: ["Pressure 10.9 bar", "Slow cylinder response"],
    diagnosis: "Relief valve set point drifted low.",
    action: "Relief valve recalibration",
    outcome: "resolved",
    technician: "Sana P.",
    technicianNotes:
      "Relief valve creeping open at 11.8 bar. Recalibrated set point to 12.6 bar and verified with dead-weight tester.",
    learning: "P-04 pressure complaints: verify relief valve calibration before pump overhaul.",
    severity: "medium",
    timestamp: "2026-01-12T07:50:00Z",
  },
  {
    code: "MEM-P04-E118-0526",
    incidentCode: "INC-P04-0526",
    machineCode: "P-04",
    fault: "Hydraulic fluid overheating",
    errorCode: "E118",
    symptoms: ["Fluid temp 74°C", "Dusty environment"],
    diagnosis: "Blocked heat exchanger fins.",
    action: "Heat exchanger cleaning",
    outcome: "resolved",
    technician: "Vikram D.",
    technicianNotes:
      "Heat exchanger fins clogged with dust. Compressed-air cleaning restored ΔT; fluid temp back under 60°C.",
    learning: "P-04 overheating in summer months is usually exchanger fouling, not pump wear.",
    severity: "medium",
    timestamp: "2026-05-08T13:20:00Z",
  },
  {
    code: "MEM-P04-E301-0826",
    incidentCode: "INC-P04-0826",
    machineCode: "P-04",
    fault: "Intermittent pressure drop",
    errorCode: "E301",
    symptoms: ["Cavitation noise at start-up", "Pressure dips"],
    diagnosis: "Suction strainer restriction causing cavitation.",
    action: "Suction strainer replacement",
    outcome: "resolved",
    technician: "Sana P.",
    technicianNotes:
      "Cavitation noise audible on start-up. Suction strainer 70% blocked; replaced and de-aerated circuit.",
    learning: "Recurring E301 on P-04: check suction strainer — second occurrence in 2026.",
    severity: "low",
    timestamp: "2026-08-19T10:10:00Z",
  },
  {
    code: "MEM-G02-E210-0226",
    incidentCode: "INC-G02-0226",
    machineCode: "G-02",
    fault: "Coolant temperature high",
    errorCode: "E210",
    symptoms: ["Coolant 96°C", "Visible coolant loss"],
    diagnosis: "Corroded radiator core.",
    action: "Radiator core replacement",
    outcome: "resolved",
    technician: "Vikram D.",
    technicianNotes:
      "Radiator core internally corroded. Replaced core, flushed jacket, refilled with 50/50 coolant. Load test at 80% for 2h stable.",
    learning: "G-02 coolant events: pressure-test radiator; jacket flush needed with core change.",
    severity: "high",
    timestamp: "2026-02-14T06:30:00Z",
  },
  {
    code: "MEM-G02-E405-0526",
    incidentCode: "INC-G02-0526",
    machineCode: "G-02",
    fault: "Governor hunting",
    errorCode: "E405",
    symptoms: ["Frequency swings ±0.8 Hz", "Erratic rpm"],
    diagnosis: "Sticking governor linkage.",
    action: "Governor linkage service",
    outcome: "resolved",
    technician: "Arjun K.",
    technicianNotes:
      "Governor linkage sticking due to gummed oil. Cleaned, re-greased, droop reset. Frequency stable at 50.0 Hz.",
    learning: "G-02 governor hunting responds to linkage service — no governor replacement needed.",
    severity: "medium",
    timestamp: "2026-05-22T15:45:00Z",
  },
  {
    code: "MEM-G02-E204-0726",
    incidentCode: "INC-G02-0726",
    machineCode: "G-02",
    fault: "High vibration",
    errorCode: "E204",
    symptoms: ["Vibration 7.1 mm/s at DE", "Steady with load"],
    diagnosis: "Alternator DE bearing wear suspected.",
    action: "Bearing replacement",
    outcome: "failed",
    technician: "Karthik R.",
    technicianNotes:
      "Replaced DE bearing on alternator. Vibration improved marginally (7.1 to 6.6 mm/s) but returned within 48h. Rotor balancing suspected.",
    learning:
      "G-02 vibration did not respond to bearing replacement — rotor balance is the outstanding suspect.",
    severity: "high",
    timestamp: "2026-07-11T09:00:00Z",
  },
  {
    code: "MEM-G02-E330-0926",
    incidentCode: "INC-G02-0926",
    machineCode: "G-02",
    fault: "Exhaust smoke at load",
    errorCode: "E330",
    symptoms: ["Smoke above 75% load", "Slightly high fuel rate"],
    diagnosis: "Injector spray pattern degradation.",
    action: "Injector servicing",
    outcome: "partial",
    technician: "Vikram D.",
    technicianNotes:
      "Two injectors re-calibrated, smoke reduced but still visible above 75% load. Fuel analysis pending — possible cetane issue.",
    learning: "G-02 smoke at load may persist after injector service — pull fuel sample if it returns.",
    severity: "medium",
    timestamp: "2026-09-08T12:40:00Z",
  },
  {
    code: "MEM-M12-E501-0426",
    incidentCode: "INC-M12-0426",
    machineCode: "M-12",
    fault: "Winding temperature alarm",
    errorCode: "E501",
    symptoms: ["Winding temp 91°C", "Fibre dust environment"],
    diagnosis: "Blocked cooling airflow.",
    action: "Cooling fan cleaning",
    outcome: "resolved",
    technician: "Sana P.",
    technicianNotes:
      "Cowl screen blocked with fibre dust. Cleaned fan cowl and frame air paths; winding temp back to 68°C from 91°C.",
    learning: "M-12 E501: always check cowl screen first — fibre dust packs monthly.",
    severity: "medium",
    timestamp: "2026-04-03T08:15:00Z",
  },
  {
    code: "MEM-M12-E204-0826",
    incidentCode: "INC-M12-0826b",
    machineCode: "M-12",
    fault: "Bearing noise",
    errorCode: "E204",
    symptoms: ["Audible roughness at NDE", "Vibration 3.8 mm/s"],
    diagnosis: "Dry NDE bearing.",
    action: "Bearing lubrication",
    outcome: "resolved",
    technician: "Karthik R.",
    technicianNotes:
      "NDE bearing dry. Greased with correct quantity (12 g, 6312-2Z). Noise gone; vibration down to 2.0 mm/s.",
    learning: "M-12 bearing noise in early stages is resolved by greasing to spec, not replacement.",
    severity: "low",
    timestamp: "2026-08-14T11:05:00Z",
  },
  {
    code: "MEM-D08-E420-0326",
    incidentCode: "INC-D08-0326",
    machineCode: "D-08",
    fault: "Belt tracking drift",
    errorCode: "E420",
    symptoms: ["Belt edge wear on drive side", "Drift to right"],
    diagnosis: "Head pulley out of square.",
    action: "Pulley alignment",
    outcome: "resolved",
    technician: "Meera S.",
    technicianNotes:
      "Head pulley out of square by 2 mm. Re-squared and re-tensioned belt to 4.5% elongation spec.",
    learning: "D-08 tracking drift: check pulley squareness before adjusting tension.",
    severity: "low",
    timestamp: "2026-03-09T10:55:00Z",
  },
  {
    code: "MEM-D08-E115-0626",
    incidentCode: "INC-D08-0626",
    machineCode: "D-08",
    fault: "Gearbox oil leak",
    errorCode: "E115",
    symptoms: ["Oil film under input shaft", "Level dropping"],
    diagnosis: "Hardened input shaft seal; plugged breather raising case pressure.",
    action: "Shaft seal replacement",
    outcome: "resolved",
    technician: "Vikram D.",
    technicianNotes:
      "Input shaft seal hardened and cracked. Replaced seal, checked breather (was plugged), cleaned breather and refilled to sight glass.",
    learning: "D-08 seal failures coincide with plugged breathers — always service breather with seal.",
    severity: "medium",
    timestamp: "2026-06-27T14:30:00Z",
  },
  {
    code: "MEM-D08-E204-0926",
    incidentCode: "INC-D08-0926",
    machineCode: "D-08",
    fault: "Vibration spike at speed",
    errorCode: "E204",
    symptoms: ["Vibration 5.1 mm/s at 42 Hz", "Roughness under load"],
    diagnosis: "Worn pulley lagging.",
    action: "Pulley lagging repair",
    outcome: "partial",
    technician: "Arjun K.",
    technicianNotes:
      "Re-lagged head pulley. Vibration reduced 5.1 to 3.4 mm/s but slight roughness remains at 42 Hz. Monitor trend.",
    learning: "D-08 lagging repair reduced but did not clear vibration — residual 42 Hz component needs monitoring.",
    severity: "high",
    timestamp: "2026-09-12T09:20:00Z",
  },
  {
    code: "MEM-A06-E301-0126",
    incidentCode: "INC-A06-0126",
    machineCode: "A-06",
    fault: "Low discharge pressure",
    errorCode: "E301",
    symptoms: ["Discharge 7.1 bar", "Separator ΔP high"],
    diagnosis: "Saturated air/oil separator element.",
    action: "Air/oil separator replacement",
    outcome: "resolved",
    technician: "Sana P.",
    technicianNotes:
      "Separator element ΔP 0.9 bar. Replaced element, pressure recovered to 8.2 bar. Logged element in spares tracking.",
    learning: "A-06 pressure loss tracks separator ΔP — replace element at 0.8 bar differential.",
    severity: "medium",
    timestamp: "2026-01-28T08:00:00Z",
  },
  {
    code: "MEM-A06-E502-0626",
    incidentCode: "INC-A06-0626",
    machineCode: "A-06",
    fault: "Unloader fault",
    errorCode: "E502",
    symptoms: ["Constant-load running", "Short cycling"],
    diagnosis: "Failed unloader solenoid coil.",
    action: "Solenoid valve replacement",
    outcome: "resolved",
    technician: "Karthik R.",
    technicianNotes:
      "Unloader solenoid coil open-circuit. Replaced valve; unload cycle verified at 8.6 bar.",
    learning: "A-06 E502 is a consumable solenoid — keep two spares.",
    severity: "low",
    timestamp: "2026-06-05T13:40:00Z",
  },
  {
    code: "MEM-A06-E204-0826",
    incidentCode: "INC-A06-0826",
    machineCode: "A-06",
    fault: "High vibration",
    errorCode: "E204",
    symptoms: ["Vibration 4.9 mm/s", "After foundation work nearby"],
    diagnosis: "Coupling misalignment introduced by foundation settlement.",
    action: "Motor alignment correction",
    outcome: "resolved",
    technician: "Meera S.",
    technicianNotes:
      "Compressor-motor coupling misaligned 0.22 mm after foundation work. Laser-aligned; vibration 4.9 to 3.8 mm/s.",
    learning: "A-06 vibration after civil works nearby: alignment check first (0.22 mm found in Aug).",
    severity: "medium",
    timestamp: "2026-08-25T14:15:00Z",
  },
  {
    code: "MEM-P09-E310-0226",
    incidentCode: "INC-P09-0226",
    machineCode: "P-09",
    fault: "Cavitation noise",
    errorCode: "E310",
    symptoms: ["Gravel noise at suction", "Flow fluctuation"],
    diagnosis: "Blocked suction strainer.",
    action: "Suction strainer cleaning",
    outcome: "resolved",
    technician: "Meera S.",
    technicianNotes:
      "Strainer basket 60% blocked with scale. Cleaned; NPSH margin restored, noise gone.",
    learning: "P-09 cavitation: clean strainer quarterly during scale season.",
    severity: "medium",
    timestamp: "2026-02-20T07:25:00Z",
  },
  {
    code: "MEM-P09-E118-0726",
    incidentCode: "INC-P09-0726",
    machineCode: "P-09",
    fault: "Seal weeping",
    errorCode: "E118",
    symptoms: ["Visible drip 4 drops/min", "Vapour at gland"],
    diagnosis: "Scored mechanical seal faces.",
    action: "Mechanical seal replacement",
    outcome: "resolved",
    technician: "Sana P.",
    technicianNotes:
      "Seal faces scored. Replaced mechanical seal and throat bushing; leak rate now zero.",
    learning: "P-09 weeping seals: replace full seal kit, not just faces.",
    severity: "low",
    timestamp: "2026-07-19T15:10:00Z",
  },
  {
    code: "MEM-P09-E204-0926",
    incidentCode: "INC-P09-0926",
    machineCode: "P-09",
    fault: "High vibration",
    errorCode: "E204",
    symptoms: ["Vibration 5.6 mm/s", "Bearing fluting pattern on raceway"],
    diagnosis: "Shaft-current fluting of motor DE bearing.",
    action: "Bearing replacement",
    outcome: "resolved",
    technician: "Karthik R.",
    technicianNotes:
      "Motor DE bearing fluting from shaft currents confirmed. Replaced bearing and fitted insulated sleeve. Vibration 5.6 to 2.6 mm/s.",
    learning:
      "P-09 bearing replacement works when fluting confirmed — fit insulated sleeve to prevent repeat.",
    severity: "medium",
    timestamp: "2026-09-05T08:45:00Z",
  },
  {
    code: "MEM-T03-E405-0126",
    incidentCode: "INC-T03-0126",
    machineCode: "T-03",
    fault: "Governing valve sticking",
    errorCode: "E405",
    symptoms: ["Stick-slip on load changes", "Slow response"],
    diagnosis: "Valve stem deposits.",
    action: "Governing valve overhaul",
    outcome: "resolved",
    technician: "Arjun K.",
    technicianNotes:
      "Valve stem deposits causing stick-slip. Overhauled valve, cleaned stem, renewed packing. Response linear across 20-100%.",
    learning: "T-03 valve stick-slip returns after ~6 months — schedule preventive overhaul.",
    severity: "high",
    timestamp: "2026-01-15T11:50:00Z",
  },
  {
    code: "MEM-T03-E204-0426",
    incidentCode: "INC-T03-0426",
    machineCode: "T-03",
    fault: "High vibration",
    errorCode: "E204",
    symptoms: ["Vibration 7.0 mm/s", "Concentrated 1× at rated speed"],
    diagnosis: "Journal bearing wear assumed.",
    action: "Bearing replacement",
    outcome: "failed",
    technician: "Karthik R.",
    technicianNotes:
      "Replaced #2 journal bearing. Vibration unchanged (7.0 mm/s). Balancing plant visit needed; scheduled for next shutdown window.",
    learning:
      "T-03 vibration is not bearing-related — #2 journal bearing replacement changed nothing (Apr 2026).",
    severity: "high",
    timestamp: "2026-04-18T10:05:00Z",
  },
  {
    code: "MEM-T03-E204-0626",
    incidentCode: "INC-T03-0626",
    machineCode: "T-03",
    fault: "High vibration",
    errorCode: "E204",
    symptoms: ["Vibration 7.0 mm/s", "Phase stable"],
    diagnosis: "Rotor imbalance.",
    action: "Rotor field balancing",
    outcome: "partial",
    technician: "Vikram D.",
    technicianNotes:
      "Added 34 g correction mass at plane 2. Vibration 7.0 to 5.9 mm/s at rated speed. Third harmonic still elevated; further trim planned.",
    learning: "T-03 rotor balancing helps but needs a second trim pass — third harmonic remains.",
    severity: "high",
    timestamp: "2026-06-02T16:20:00Z",
  },
  {
    code: "MEM-T03-E210-0826",
    incidentCode: "INC-T03-0826",
    machineCode: "T-03",
    fault: "Steam gland leak",
    errorCode: "E210",
    symptoms: ["Steam plume at HP gland", "Vacuum degrading"],
    diagnosis: "Extruded gland packing.",
    action: "Gland seal renewal",
    outcome: "resolved",
    technician: "Meera S.",
    technicianNotes:
      "Gland packing extruded on HP side. Renewed packing rings, verified vacuum held at -92 kPa.",
    learning: "T-03 gland leaks: renew full packing set and verify vacuum under load.",
    severity: "medium",
    timestamp: "2026-08-09T09:35:00Z",
  },
];
